### PR TITLE
Deploy

### PR DESCRIPTION
**Pull request by rajeshkumarrs**
PR for Adding argparse and rich to improve user experience #5

Added argparse and rich format to deploy, delete and update python programs. The pretty print is similar to the gif attached in the issue.

### CODE REVIEW

**Comment by jjmachan** [comment]
hey @rajeshkumarrs Thanks for putting up the PR, really appreciate it 😄 . Seems like there is a conflict you might have to rebase it with the current `main` branch to fix it. Also, there are a few extra commits that are there from the previous PR that was merged it would be great if you can remove that too.

**Comment by rajeshkumarrs** [comment]
Thanks @jjmachan ... I have rebased and pushed the code again .. all conflicts seem to be resolved now.

**Comment by jjmachan** [comment]
Well done @rajeshkumarrs !! The merge conflict is resolved but if you can do one more thing that would be super helpful. 
Right now there are 11 commits and the top 3 are duplicates from another branch. While the rest have the same commit message, it would be a good idea to clean up the commits but using an interactive rebase command [ref: https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history] will make the PR super clean. Can you give that a try too?

**Comment by rajeshkumarrs** [comment]
@jjmachan .. I tried to modify the commits as you said. Hope this is fine :-)

**Pull request closed without merging**
